syntax = "proto3";
package inventory_service.v1;

import "google/api/annotations.proto";

// IMPORT_PATH → the full Go module path where the generated code will live.
// PACKAGE_NAME → the Go package name to use in the generated code.
option go_package = "github.com/yakomisar/inventory_service/pkg/pb/inventory_service/v1;v1"; // IMPORT_PATH;PACKAGE_NAME

service InventoryService {
  rpc GetItem(GetItemRequest) returns (GetItemResponse) {
    option (google.api.http) = {get: "/v1/items/{id}"};
  }

  rpc Ping(PingRequest) returns (PingResponse) {}
}

message GetItemRequest {
  string id = 1;
}
message GetItemResponse {
  string name = 1;
}

message PingRequest {}
message PingResponse {
  string message = 1;
}
